name: Python Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.3"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --dev
      - name: Run tests
        run: uv run pytest tests
      - name: Run doctest
        run: uv run pytest --doctest-glob="README.md" README.md
