name: Deploy documentation
on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"
          enable-cache: true
      - name: Build documentation
        run: |
          mkdir site
          echo '<!DOCTYPE html><meta charset="utf-8"><title>Redirecting...</title><meta http-equiv="refresh" content="0; URL=git/">' > site/index.html
          uv sync --group docs
          export LATEST_GIT_COMMIT="git-$(git rev-parse --short HEAD)"
          uv run make -C docs html
          mkdir site/git
          mv docs/_build/html/* site/git
          for tag in $(git tag --sort=-v:refname); do
            if [ "$tag" = "v0.0.0" ]; then
              continue
            fi
            git checkout -f $tag
            uv sync --group docs
            rm -r docs/_build
            DOCS_VERSION=$tag uv run make -C docs html
            mkdir site/$tag
            mv docs/_build/html/* site/$tag
          done
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
