name: Deploy documentation
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --group docs
      - name: Build documentation
        working-directory: ./docs
        run: |
          DOCS_VERSION=git uv run make html
          CURRENT_COMMIT=$(git rev-parse HEAD)
          for tag in $(git tag --sort=-v:refname); do
            git checkout --quiet tags/$tag
            uv sync --group docs
            DOCS_VERSION=$tag uv run make html
          done
          git checkout --quiet $CURRENT_COMMIT
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_build/html
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
